### ISSUE TITLE
"Recent activity" screen and truncated addresses

### ISSUE THREAD

**Issue by Bec-de-Xorbin** [LayoutXML/SABS#1]
Area for blocked address names is too narrow and addresses get truncated. Same thing with landscape mode. 

![screenshot_20180209-222334_sabs](https://user-images.githubusercontent.com/1503339/36048744-f8cf1b1e-0de8-11e8-94a8-1e6d0a31633e.jpg)

![screenshot_20180209-222354_sabs](https://user-images.githubusercontent.com/1503339/36048754-0119b5b8-0de9-11e8-9e74-125cf38507ee.jpg)

**Comment by tam481** [comment]
Please reduce the font size. It's too big and it takes up too much space on the screen.

**Comment by LayoutXML** [comment]
Issue fixed. Changes will be available on the next update

**Comment by Mike-BITW** [comment]
MUCH better!
