### ISSUE TITLE
New/Better Title for App

### ISSUE THREAD

**Issue by alkoforumm** [LayoutXML/SABS#11]
Aside from the xda thread it would be maybe a good idea to slightly change the name of the projekt since its more than an adblocker..
This issue could be a list for all to send some ideas in..
If you disagree close the issue right away.

**Comment by Mike-BITW** [comment]
Yes, this is actually simply(?) a Knox front end, much like AdAway is a hosts file manager, but changing the name now would probably cause too much confusion.  AdHell, AdAway and SABS are not ad blockers, "googleadservices.com" is not a URL, Java is interpreted and not compiled, MS Windows is not an OS, etc...  "_What's in a name? That which we call SABS By any other name would be as good_" (slightly adapted from Billy Shakespear, Romeo & Juliet, Act II, scene 2... ;)

**Comment by alkoforumm** [comment]
> Yes, this is actually simply(?) a Knox front end,

That was my intention to reflect it more that this is a knox front end, I am quite unsure how much confusion it would really generate. :)

**Comment by LayoutXML** [comment]
I couldn't come up with a better thread name and the primary function of SABS is adblocking (it's even in the SABS name). If you have better suggestions, please let me know.

**Comment by LayoutXML** [comment]
Added "(KNOX front end)" to both github and xda thread.
