### ISSUE TITLE
Little UI flaw

### ISSUE THREAD

**Issue by almightyNTER** [LayoutXML/SABS#13]
The "S" letter in DNS is a little bit chipped off. Not an actual bug, just a UX flaw.

https://i.imgur.com/JvAzNsZ.jpg

**Comment by LayoutXML** [comment]
What phone model is that?

**Comment by almightyNTER** [comment]
It's an S8, SM-G950F

**Comment by motfis** [comment]
Another UI problem
https://imgur.com/a/pRv77
Note FE, SM-N935, Nougat 7.0

**Comment by CitizenXVIL** [comment]
Similar UI problem to above.

https://imgur.com/sRmrY08

S8, Oreo beta.

**Comment by LayoutXML** [comment]
@motfis & @CitizenXVIL it should be fixed with the latest commit. If you have installed it by renaming package name on apk, you'll have to wait for a new release.

**Comment by LayoutXML** [comment]
@almightyNTER issue should be fixed now. Wait for a new release. It took this long because I wanted to use a normal dialog builder and replace the dialog fragment. Unfortunately, it didn't work out. Reopen the issue if the issue is not fixed on your device with the next (0.0.9) release
