### ISSUE TITLE
Whitelist some apps by default

### ISSUE THREAD

**Issue by eXPerience83** [LayoutXML/SABS#17]
Please, whitelist Google Allo, Duo, Google Music and Youtube by default. And whitelist Samsung Pay and Samsung Members by default too. Because if not, it's not possible to access to promotions, at least in Spain.
For example, I can't login to Samsung Members if I don't Whitelist the app. Maybe we can found the domain to whitelist it and not the app.

**Comment by LayoutXML** [comment]
Google Allo, Duo and Music is whitelisted by default but this change is not released yet (unless you compile from source)

I will add those two other apps.

**Comment by Mike-BITW** [comment]
Please don't add the Samsung ones!  Some of use use Samsung Pay heavily but don't have any interest in promotions or "Members" (whatever that is).  I don't even think Allo/Duo/Music should be whitelisted by default. A suggestion in the documentation if probably more than enough.

**Comment by LayoutXML** [comment]
Allo, duo and music must be whitelisted because they don't show ads and otherwise domains they use are blocked. Usually they start draining battery because they constantly try to communicate with a blocked domain because they can't access it.

**Comment by LayoutXML** [comment]
Upon further consideration I have decided to not add those apps to whitelist by default because users can whitelist them themselves if they want to. Default whitelisted apps won't be removed either because they cause major issues.

**Comment by LayoutXML** [comment]
To add to that, apps are whitelisted only once and it's up to user to leave them whitelisted.

**Comment by eXPerience83** [comment]
And an option just like the"block port 53" on miscellaneous?
Thank you.
I think I can see the blocked domain on the recent activity, and try to whitelist the it.
Thank you

**Comment by LayoutXML** [comment]
I don't think adding an option just to unblock Samsung ads is worth the time. It takes roughly the same amount of clicks from the user's perspective as well.
You can easily whitelist **apps** in settings. It's way easier than whitelisting domains because to whitelist domain you have to find the actual domain on hosts file (on github)(at the moment) - which may be a wildcard, then type it in settings, turn blocking off and on. Whitelisting apps takes just one click.
