### ISSUE TITLE
unstable warning

### ISSUE THREAD

**Issue by motfis** [LayoutXML/SABS#2]
The app give some warning notification everytime I open the app
![screenshot_20180210-214349](https://user-images.githubusercontent.com/8572695/36062352-1c57bf8a-0eae-11e8-8c7a-6175b8c19494.png)

**Comment by tam481** [comment]
+1
Same here.

**Comment by LayoutXML** [comment]
This is intentional. You don't want to press something accidentally in your pocket and not be able to turn your phone again, do you?

**Comment by LayoutXML** [comment]
Added option to disable warning
