### ISSUE TITLE
App is never abe to activate my Enterprise key

### ISSUE THREAD

**Issue by beavermanthatstealsstuff** [LayoutXML/SABS#21]
All it says when I try to activate it is "License activation failed.  Try again." on the bottom of the screen.

Edit: for clarification, the key does not start with KLM.  Also, I tap on "Submit KNOX Key" before tapping "Activate License.  I also already enabled device administrator privileges.

**Comment by LayoutXML** [comment]
Screenshot the place where you have copied the key from.

**Comment by koppa** [comment]
I have the same problem, so here is a screenshot of my sdk panel
I try to use the lowest key: <https://i.imgur.com/zs1VS6i.png>

**Comment by LayoutXML** [comment]
This is the wrong key. Copy from under legacy keys.
![screenshot_20180304-105549](https://user-images.githubusercontent.com/34867100/36943921-ad584ff2-1f9a-11e8-93b5-5d930c8d8d69.jpg)

**Comment by LayoutXML** [comment]
I cannot control whether Samsung activates the license or not. Up until this day there haven't been a single instance where license activation has not been a user error.

**Comment by beavermanthatstealsstuff** [comment]
I use the Enterprise key that you showed in your screenshot though

**Comment by LayoutXML** [comment]
Under legacy? Even if you use the right key and it still doesn't activate (assuming you have changed the package name), there is nothing I can do. Contact Samsung and complain that you can't develop for knox because license is not activating.

**Comment by beavermanthatstealsstuff** [comment]
When I tried to change the package name (using your instructions and APK Editor) it was already set to com.layoutxm1.sabs so I didn't change that.  The app didn't let me change it anyway, something about it "most likely not working anyway"

**Comment by Mike-BITW** [comment]
That explains it!  If you didn't change the package name it won't activate with any key.  Do not use the "com.layoutxm1.sabs" name, that's what you need to change.  Also make sure you use "APK Editor **Pro**", not just plain "APK Editor".  You can find the right app at http://www.apkeditorfree.com/
