### ISSUE TITLE
Facebook login based apps do not work out of the box

### ISSUE THREAD

**Issue by joelalmeidaptg** [LayoutXML/SABS#22]
Hello, I installed the app yesterday (since adhell stopped working) and everything is working fine, except something I noticed this morning.

If you have SABS enabled you can't login to any Facebook login based app (in my case it was Tinder), and if you clear for example the data from the apps Facebook or Messenger and try to login again you will be unable to. 

I understand this issue is not related to the code of the source but this might put away new users who find themselves unable to login to certain services, so it might be a good idea to fix it in the hosts list. 

Whitelisting graph.facebook.com and disabling/enabling SABS fixed all the issues for me.

**Comment by mmotti** [comment]
Unfortunately it sounds like you have to choose between Facebook ad choices or working Facebook integrated apps :(

Or whitelist Tinder etc.

**Comment by LayoutXML** [comment]
In addition to that, it seems that the Tinder app uses different login mechanism and doesn't let you login with graph.facebook.com blocked whereas other apps allow that. Or the login mechanism is different when logging in with Facebook installed on the phone. I use facebook in the browser with notifications enabled to save battery and have not experienced any issues with logging in with facebook on other apps.

**Comment by joelalmeidaptg** [comment]
It's not choosing between Tinder or Apps

Try to wipe the data from Facebook or Messenger, and try to login into them while you have the adblocker on. Messenger will show a message "logging in" and right after "logging out" and goes back to the login page. I can reproduce this how many times I want. This "aggressiveness" of the blocker is making these two apps (that most people use) unusable (for new users) and most of the people won't even notice it's the adblock and not the Facebook apps acting up.

**Comment by Mike-BITW** [comment]
@joelalmeidaptg: As you point out, the issue is not SABS  but simply your choice of hosts list(s).  I temporarily "borrowed" my spouse's Facebook info (I'm not a FB user), enabled SABS with only @mmotti's package, and had no trouble with FB or its Messenger and even a couple apps that login through FB, while still not seeing any FB "choice" ads. Since you were apparently happy with what your old AdHell was blocking, have you tried simply using that same old list?

**Comment by mmotti** [comment]
Just to be sure - Did you grab the most recent list? There was a time where
I forgot to put graph.facebook.com back in.

If you still have the details, might be useful to update host files,
deactivate and activate adblocking, clear Facebook data and try to login
again.

I don't have Facebook myself, either :-)

**Comment by joelalmeidaptg** [comment]
I just did the following:

- Removed the graph.facebook.com from the whitelist
- Updated the lists using UPDATE ALL from Subscribe to providers (I have the two default lists selected)
- Disabed and enabled the app
- Tried to open Tinder

Result: https://imgur.com/a/b7a4k

I can't screenshot the Messenger behavior because it goes too fast.

For me this is not really a problem since I know how to whitelist it (I discovered that it was graph.facebook.com because it was appearing in common in all three apps) but it might be for new and not so experienced users since the app is destroying functionality of certain apps. I'm just informing :)

**Comment by mmotti** [comment]
This certainly does bring an interesting issue into play as whitelisting
this also unblocks Facebook ad choices which are as obtrusive as the Google
ads.

I too am concerned about the impact on the majority of users though who
will just use the standard lists. Perhaps I'll remove this from my host
file and see what the fallout is.

**Comment by joelalmeidaptg** [comment]
Here is a video I just recorded of the behavior:

https://1drv.ms/v/s!AtiTSznCSz-k1TxrXbpn-GKLTw_W

Again, I did not change any of the list settings that come with the app, I just followed the tutorial in your page

**Comment by joelalmeidaptg** [comment]
Youtube link: https://youtu.be/OtEo41gDD5M

**Comment by joelalmeidaptg** [comment]
Yeah, maybe giving the user the option to choose would be the best thing to do. I know Facebook might have intrusive ads but having it breaking Messenger for me is a deal breaker since we at the university + family all use it for communication.

**Comment by Mike-BITW** [comment]
Thanks for the vid.  Is that with still both default lists?  Do you have the same issue when using Messenger Lite instead of the full Messenger?

**Comment by joelalmeidaptg** [comment]
Yes, default lists. I just tried the Messenger Lite and it does login. When I do it in the Facebook app it asks me for my user, password, then sends the code through SMS. When I put the code it gets me back to the login page (similarly to the Messenger app).

**Comment by Mike-BITW** [comment]
Try only ONE of the default lists (@mmotti's?).  That said, if Messenger Lite works it seem to be highly preferable to unleashing all those &^%$# FB ads when you use the full Messenger.  It's all about choices.

OT comment: It's too bad that so much energy is spent trying to second guess what various crappy apps and sites are doing, taking focus away from SABS itself, but  everything that even suggests that it can "remove ads" seems to suffer the same fate, on any platform. I wish users could learn to simply "DON'T DO THAT".  Selfishly, I'm glad that my own 150-line list allows me to use all my apps and browse all the sites I want without showing me any blockable garbage... ;)

**Comment by joelalmeidaptg** [comment]
But I don't see any ad in Facebook Messenger? I think the ads are not coming from that domain. I have never seen any ad in Facebook Messenger/Facebook with Adhell and now with SABS. I mean, I see sponsored posts in Facebook and Instagram but I think that's normal? My friends (without adblocking) do see ads in Messenger but I don't see any

**Comment by mmotti** [comment]
I have removed graph.facebook.com from my host file.

Facebook AdChoices ads don't just appear on Facebook, but in other apps too under the graph.facebook.com domain.

**Comment by Mike-BITW** [comment]
A reminder that since graph.Facebook.com is still in @LayoutXML's package, users who enable both lists won't see a difference.
