### ISSUE TITLE
SABS crashes

### ISSUE THREAD

**Issue by the4anoni** [LayoutXML/SABS#24]
Like in topic. Changed package name in android studio and activated is as device admin.
When i run it it work for 5 secoonds. After that i only see SABS has stopped working.
It crashes when i have to enter license key.
Galaxy Tab 4 7.0 LTE SM-T235
Android 5.1.1
Security patch 01.08.2017
ASKS 1.2 Release 161011
KNOX 2.4.1
KNOX Warranty Void 0x1

**Comment by LayoutXML** [comment]
It's awesome that you have used Android Studio. Can you connect your phone to your computer, press shift+f10, open logcat on pc in lower bottom, wait for crash and copy the issue here. It should be in red.

**Comment by Mike-BITW** [comment]
You tripped your Knox e-fuse? Are you under original unrooted Samsung firmware?

**Comment by the4anoni** [comment]
@LayoutXML Ok ,i'll do it tomorrow
@Mike-BITW Yes ,knox is 0x1 ,also (for now) i'm on stock nonrooted newest samsung firmware

**Comment by LayoutXML** [comment]
Yeah but triggered knox may make SABS not work and that may be the reason for your crashes

**Comment by the4anoni** [comment]
Ok ,so i am closing issue
