### ISSUE TITLE
Change whitelist code

### ISSUE THREAD

**Issue by mmotti** [LayoutXML/SABS#25]
Might be worth changing how whitelisting is currently processed.

At the moment, 7000k+ entries need to be matched x amount of times each which is not efficient.

Best bet may be to adjust the dB query to exclude the domains before they are passed through for processing.

Probably have to construct a dynamic dB query whilst looping through each whitelist entry, then send the query to the dB.

**Comment by LayoutXML** [comment]
I've actually recently found out that whitelist actually takes priority over blocking in knox which is contrary to what I've read before. We (I?) could change the code to add it as a rule which would exclude some domains that people want to unblock even if they are blocked by wildcard domain. There could even be a whitelist package where some websites that for example are not ads but domains start with ad.* or something like that. I'm not preparing for my exam but will do something about that and this issue later

**Comment by mmotti** [comment]
Does it? I thought I read in the API that the most restrictive rule wins?

The following seems to apply for IP address rules, but I can't find it
under the domain filter rules:

*NOTE: *Users may add conflicting rules for IP addresses and domain names.
In this case, the more restrictive rule always takes precedence.

If this is the case, though, you can pass an 'allowlist' alongside the
denylist; packagename, denylist, allowlist

I think adhell was coded to pass an empty array in place of the allow list
just so the firewall will accept it. We will always have a bit of an issue
with whitelisting though due to our use of wildcards on deny rules.

We have some experimenting to do but it looks like we have 2 options to
explore. Filtering dB results and exploring the provided 'allowlist'
functionality.

**Comment by Mike-BITW** [comment]
Ideally it would be useful to add a "test" screen, allowing users to enter a URL then see if it would be blocked or allowed with their current settings, maybe even showing specifically which black/white entries are relevant. 

I still think that a future option to save/load the current active black (remote providers + local blacklist) and white lists locally, and use that instead of remote URLs would allow users to better customize their configuration. I'm not aware of any common "ad blocker" that can rely primarily on a  local file, and that would make SABS drastically better once users understand that updating from a remote list every 5 minutes is pointless. It was under consideration for AdAway at one time, but then AdAway got all tangled up in endless workarounds for various "partial root" methods (systemless, Magisk, etc.).

**Comment by mmotti** [comment]
This may be a little tricky as the actual 'deny' list isn't compiled until
the blocker 'enable' button is pushed. I have also yet to find a way to
match against a java arraylist without having to iterate through thousands
of entries to match against each iteration. Match, specifically, as it
needs a regex check with our inclusion of wildcards.

My current code for the whitelist will be capable of checking whether a
particular url is in the deny list.. It might just need some fine tuning on
the regex. Also we need some way in which to have a denylist ready outside
of the 'enable' screen.

The other option would be to have a simple field to enter a domain to try
and do a http request and see if we can check the response code but that
would only give us an indication of what's blocked for the current rules in
the firewall, not for those we've yet to add.

I've not explored the domain filter report part of the api yet, but I'm
assuming that's where the recent activity comes from. I wonder whether this
includes not only the domain that was blocked, but also the rule that
caused it to be blocked - This would be extremely useful if it is available
and we are able to display it. Would make whitelisting so much easier and
not so confusing with wildcards e.g. *yimg.com blocking ebayimg.com, yet
user confusion when whitelisting ebayimg.com does nothing.

**Comment by Mike-BITW** [comment]
Everything is tricky in Java, one of the reasons I don't volunteer code fragments.  Testing the http(s) request would be better than nothing but probably not worth the trouble since it's just as easy to use ping, curl or, for most users, a full browser.

**Comment by LayoutXML** [comment]
Read this: https://support.samsungknox.com/hc/en-us/articles/115013145547-What-is-the-order-of-precedence-for-firewall-rules-

**Comment by Mike-BITW** [comment]
Please don't worry about SABS right now.  That can wait but your upcoming test won't! ;)

**Comment by mmotti** [comment]
Fixed
