### ISSUE TITLE
Export blocked domains discrepancy

### ISSUE THREAD

**Issue by Mike-BITW** [LayoutXML/SABS#30]
@LayoutXML : When the Recent Activity shown time is set to >1 days,  the Export dialog still says "_in the last 24 hours_" (the old "last_day_blocked" string?). I can't dig into it right now, but something doesn't look quite  right. 

Also, should we remind users that the file names you use automatically get a ".txt" extension and that the extension should not be entered manually, except for providers?

**Comment by LayoutXML** [comment]
It should not be that string. I have replaced it.
![smartselectimage_2018-03-12-20-19-44](https://user-images.githubusercontent.com/34867100/37301978-d78277f0-2632-11e8-92b8-817053fb8761.jpg)

**Comment by Mike-BITW** [comment]
Not that one, the one in the export file name input dialog ("Export domains blocked in the last 24 hours to a file. Choose a file name below")

**Comment by LayoutXML** [comment]
Oh, right. Haven't noticed that

**Comment by LayoutXML** [comment]
Issue fixed
