### ISSUE TITLE
version code/build policy?

### ISSUE THREAD

**Issue by Mike-BITW** [LayoutXML/SABS#32]
Recently, we have been changing _versionCode_ to reflect the number of commits.  Creating a build number in that manner is great, but the problem is that it makes it awkward for users to backtrack and revert to a previous build.  In the future (after the next apk release) it might be wiser to leave versionCode alone during the life of that  release, but edit _versionName_ to reflect the current commit instead ("**0.0.8.526**"?) as I think I had mentioned on XDA (or maybe a PM) a while ago. That way the commit/build number is still readily available in the "About" dialog, but reverting to a previous build within that release won't require an uninstall/reinstall. Just a thought... ;)

**Comment by LayoutXML** [comment]
I think this would break the updater functionality (it notifies when the latest release version is higher).

**Comment by LayoutXML** [comment]
I don't think that people care that much about the latest commits and the number being in version name. I think the better option is to always update the version code to reflect the number of commits, and to improve version name to follow something like semantic versioning (https://semver.org/) but that better suits the android. Version name could only be used for apk releases and version code for more geeky people who have chosen the android studio path of installation (only 40 out of the 12 000).

**Comment by Mike-BITW** [comment]
The main difference is that Android doesn't care about versionName but relies on versionCode. I don't agree with your assessment, but you're the boss! ;)
