### ISSUE TITLE
Uninstall system apps

### ISSUE THREAD

**Issue by thyeestes** [LayoutXML/SABS#34]
Would it be possible to not just disable but completly uninstall system apps via SABS and Knox?

**Comment by LayoutXML** [comment]
No. Knox doesn't allow that.

**Comment by thyeestes** [comment]
Ok clear. Thanks.

**Comment by danchev** [comment]
My girlfriend had AdHell on her Verizon Galaxy S8. After updating to Android Oreo I uninstalled AdHell and installed SABS following the instructions. After activation android apps were not visible in the 'Package Disabler' or 'Manage blocking in apps' sections. 

![d60bb929-ab32-418b-9fff-9f5732d0a5ac--a43aavnlia9gdyudcwcyrsdhw](https://user-images.githubusercontent.com/12420863/37551836-8ea27d36-2976-11e8-9b02-2a2d43238c5d.jpg)
![e38363f3-8f9a-4ca6-ad63-e752a61467b1--963aavnlifxygti8be4ogt51w](https://user-images.githubusercontent.com/12420863/37551837-8eb2e54a-2976-11e8-9485-260468c7ec2a.jpg)
