### ISSUE TITLE
SABS is turned off

### ISSUE THREAD

**Issue by mrahman13** [LayoutXML/SABS#39]
When I press turn on, it keeps saying SABS is turned off

**Comment by LayoutXML** [comment]
If you have changed the package name using Android studio, please provide logs.
If you have changed the package name using APK Editor pro or other tools, app got corrupted while changing the package name - repeat the process.

**Comment by LayoutXML** [comment]
Hi again, I have just been contacted by another user who had the same issue but got it solved (maybe it was you? Messaged me on reddit two hours before you). Apparently it "was a naming error" and the solution was "tried a third time and it worked great". So, from what I understand make sure your package name is follows the 3-9-4 scheme. Replace any digits with letters if you still have problems.

**Comment by mrahman13** [comment]
yeah that was me, thank you so much again
