### ISSUE TITLE
Bin icon to remove provider sometimes doesn't work

### ISSUE THREAD

**Issue by tam481** [LayoutXML/SABS#4]
Hello,
There seems to be an issue with the bin icon to remove providers doesn't work sometimes. You have to keep tapping to remove a source. I wonder if this is because the actual "touch" area is too small compared to the size of the icon. Also, the bin icon itself seems too big and inconsistent with the overall design.

**Comment by LayoutXML** [comment]
Fixed the issue. Changes will be available on the next update.
I've spent quite a lot of time on this as the issue wasn't apparent.
