### ISSUE TITLE
Samsung A5 (2016) : Licence activation failed

### ISSUE THREAD

**Issue by LiMiNiNo** [LayoutXML/SABS#41]
I followed the instructions. (https://forum.xda-developers.com/android/apps-games/app-sabs-simple-adblocker-samsung-t3751722)

But on my Samsung A5 (2016) I always get : Licence activation failed.
No error/excepetion in the Debug log

**Comment by LayoutXML** [comment]
Can't help with anything. Activation is on Samsung's side. Make sure the key is correct (128 bite, legacy), ypu have changed the package name, knox is not tripped, you have internet connection, key is not blocked etc. You can also contact Samsung - say that you want to develop and your developer key is not working. Don't mention SABS just in case.
