### ISSUE TITLE
Not updating provider list remains 0

### ISSUE THREAD

**Issue by godey4me** [LayoutXML/SABS#46]
I had it working for a day. I added the Adaway list to my providers.  Then I noticed apps were not updating from google play store. I thought it might have to do with the Adaway list so I deleted it. Now all the default providers show 0 no matter how many times I tap updated selected. And nothing is blocked

I have uninstalled and rebooted 3 times. 
I am using Note 8
![screenshot_20180323-060521_sabs](https://user-images.githubusercontent.com/19440061/37828632-b143e966-2e61-11e8-9f31-76c264409266.jpg)

Thanks,

**Comment by godey4me** [comment]
I am on 0.0.9 version 544.

**Comment by LayoutXML** [comment]
Hi, this is normal. I have begun the transfer of standard package to another source but had not yet finished. That's why it's 0. If you update to the later commit 551, mmotti's package will work fine

**Comment by mmotti** [comment]
@godey4me update to the latest commit and if that fails, you may manually add [my host file](https://raw.githubusercontent.com/mmotti/mmotti-host-file/master/wildcard_standard_hosts.txt)

**Comment by tam481** [comment]
Just built one based on commit no. 555 and all I get is mmotti's package with 6590 entries "Standard package" has 0 but no Small or Large or Experimental

**Comment by LayoutXML** [comment]
That's how it should be at the moment

**Comment by godey4me** [comment]
Great! Used commit 555 and I get mmotti;s package. I downloaded the others onto sdcard and added them for now. Awesome work
