### ISSUE TITLE
Unable to activate.

### ISSUE THREAD

**Issue by ThatZeek** [LayoutXML/SABS#5]
Hey, so I'm on Oreo (recently updated).

I have changed (following instructions) the name of the app etc, did the whole get the key.

Literally no matter what I do, I am unable to activate.

**Comment by LayoutXML** [comment]
Sorry to hear that. I will take a look at why but I'm unable to test because I don't have a phone with Oreo. Many people already told me that it works on oreo for them so there might be an issue with your key or package id was already used by at least 10 people.

**Comment by LayoutXML** [comment]
App is fully supported for Oreo. Try again using different package name and/or license key. Make sure you have internet connection.
Issue closed due to user error
