### ISSUE TITLE
Feature Request: DNS blocking (Port 53)

### ISSUE THREAD

**Issue by tam481** [LayoutXML/SABS#6]
Hi,
Please add the option to enable DNS port 53 blocking globally and if at all possible, the ability to exclude certain apps.

Thanks in advance

Edit: Just wanted to add that I'm currently creating my own build after you commit code. I'm also un-commenting the code blocking DNS so I have DNS blocking on the build I'm running on my phone. Thanks for sorting out the "bin" icon issue.

**Comment by LayoutXML** [comment]
You can now select to block port 53 in app settings. Can't promise that excluding apps will be a feature soon
