### ISSUE TITLE
App icons don't show up for some apps

### ISSUE THREAD

**Issue by piegit** [LayoutXML/SABS#7]
![screenshot_20180217-235818_sabs](https://user-images.githubusercontent.com/23616908/36349233-ea893b0a-143e-11e8-9822-48b6f82bc91a.jpg)
any idea why this happens?

**Comment by LayoutXML** [comment]
Thanks for letting me know. This is probably because I force it to load icons from memory to speed up the scrolling and reduce lag. Will have to revert back some code so that it loaded all the icons but then scrolling is stuttering.

**Comment by LayoutXML** [comment]
*Accidentally closed the issue

**Comment by mmotti** [comment]
I've not done much work with icons yet but is it maybe possible to put a conditional icon fletcher in, only for those that aren't in memory?

**Comment by LayoutXML** [comment]
Issue fixed. Icons will be showing up on the next app version (or immediately if you build from source yourself)
