### ISSUE TITLE
Netflix (+others?) not working with blanket port 53 block

### ISSUE THREAD

**Issue by mmotti** [LayoutXML/SABS#8]
Perhaps to implement this, and to improve upon my method, it might be best to query package manager for what apps are web browsers, and then adding those package names to array to be processed by my code over at Adhell2?

It looks like you can query pm for what apps would handle an intent to say, open https://www.google.co.uk

Add the package names to an array and then for each item in the array, add a port 53 ipv4 and ipv6 deny rule.

**Comment by mmotti** [comment]
Or the quick method to only add the Chrome packages would work and the code is ready for that already.

**Comment by LayoutXML** [comment]
I simply added 4 chrome versions as of now. Will improve later but I doubt that port blocking will be necessary for other apps including chromium forks.

**Comment by tam481** [comment]
Other apps are making their own port 53 requests e.g. O2 App. Why restrict this to Chrome! It seems like a step backwards. If people don't want to block port 53, they can simply disable the blocking.

**Comment by LayoutXML** [comment]
Added option to choose
